"""
PrOxy Trading Terminal - Meta-label precision layer
===================================================

mlfinlab / Athena-X style meta-labeling: a SECONDARY model that learns,
from past trade outcomes, whether an already-approved signal is worth
taking ("will this trade actually win?").

    Primary model  : the price-action scoring engine (unchanged)
    Meta model     : XGBoost on ENTRY-TIME features only (no look-ahead)

The meta model is ADVISORY by default - it logs P(win) on every entry
(e.g. "META 63%").  Set META_CONFIRM=True in config.py to gate entries
below META_MIN_PROB.

Labels come from REAL past outcomes: 1 if the trade closed with pnl > 0,
else 0.  Training data is generated by running the backtest (same engine,
same exits) and capturing entry-time features per trade.

Entry-time features only (no exit/hold info - that would leak the label):
    signal_score, confidence, setup_strength, rsi, atr_pct, vol_ratio,
    trend (bull=1/bear=-1/flat=0), hour_of_day, pop, risk_reward
"""

import json
import os
from datetime import datetime

import numpy as np

MODELS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "models")
FEATURES = [
    "signal_score", "confidence", "setup_strength", "rsi", "atr_pct",
    "vol_ratio", "trend_code", "hour", "pop", "risk_reward",
]


def _trend_code(trend):
    return {"UPTREND": 1, "DOWNTREND": -1}.get(trend, 0)


def features_from_signal(signal, frame, cfg):
    """Entry-time feature vector from a signal + indicator frame."""
    from .indicators import rsi as _rsi, atr as _atr
    from .options import success_probability
    close = frame["close"]
    rsi_val = float(_rsi(close, cfg.RSI_PERIOD).iloc[-1]) if len(close) > cfg.RSI_PERIOD else 50.0
    atr_pct = float(_atr(frame, cfg.ATR_PERIOD).iloc[-1] / close.iloc[-1] * 100.0) if len(frame) > 5 else 0.0
    vr = float(frame["vol_ratio"].iloc[-1]) if "vol_ratio" in frame.columns else 0.0
    pop = success_probability(cfg.PROFIT_TARGET_PCT, cfg.STOP_LOSS_PCT) or 0.0
    hour = 9  # entries only happen 9:15-14:45; use bar hour when available
    ts = frame.index[-1]
    if hasattr(ts, "hour"):
        hour = ts.hour
    return {
        "signal_score": float(signal.score),
        "confidence": float(signal.confidence),
        "setup_strength": float(signal.setup_strength),
        "rsi": round(rsi_val, 2),
        "atr_pct": round(atr_pct, 3),
        "vol_ratio": round(vr, 2),
        "trend_code": _trend_code(signal.trend),
        "hour": float(hour),
        "pop": round(pop, 3),
        "risk_reward": round(cfg.PROFIT_TARGET_PCT / cfg.STOP_LOSS_PCT, 2),
    }


def _matrix(rows):
    return np.asarray([[float(r.get(f, 0.0) or 0.0) for f in FEATURES] for r in rows], dtype=float)


def train_from_trades(trades, model_type="xgboost", verbose=True):
    """
    Train the meta model from backtest/paper trade records that carry the
    entry-time features + pnl.  Splits 80/20 by time (no shuffle - walk
    forward), reports accuracy / precision / AUC-style stats.
    """
    rows = [t for t in trades if t.get("pnl") is not None and any(t.get(f) is not None for f in FEATURES)]
    if len(rows) < 120:
        raise RuntimeError(f"need >=120 labeled trades, got {len(rows)} - run a longer backtest first")
    X = _matrix(rows)
    y = np.array([1 if t["pnl"] > 0 else 0 for t in rows], dtype=int)
    split = int(len(X) * 0.8)
    X_tr, y_tr, X_te, y_te = X[:split], y[:split], X[split:], y[split:]

    if model_type == "xgboost":
        from xgboost import XGBClassifier
        model = XGBClassifier(n_estimators=220, max_depth=4, learning_rate=0.04,
                              subsample=0.85, colsample_bytree=0.85,
                              eval_metric="logloss", random_state=42)
        model.fit(X_tr, y_tr)
        proba = model.predict_proba(X_te)[:, 1]
        import joblib
        path = os.path.join(MODELS_DIR, "meta_xgboost.joblib")
        joblib.dump(model, path)
    else:
        from sklearn.ensemble import GradientBoostingClassifier
        model = GradientBoostingClassifier(n_estimators=220, max_depth=3,
                                           learning_rate=0.04, random_state=42)
        model.fit(X_tr, y_tr)
        proba = model.predict_proba(X_te)[:, 1]
        import joblib
        path = os.path.join(MODELS_DIR, "meta_gb.joblib")
        joblib.dump(model, path)

    pred = (proba >= 0.5).astype(int)
    acc = float(np.mean(pred == y_te))
    pos = y_te == 1
    if pos.sum():
        # when the model says YES confidently (>=0.6), how often is it right?
        confident = proba >= 0.6
        conf_prec = float(np.mean(y_te[confident] == 1)) if confident.sum() else None
    else:
        conf_prec = None
    meta = {
        "model": model_type, "trained_at": datetime.now().isoformat(),
        "samples": len(rows), "test_samples": len(y_te),
        "positive_rate": round(float(y_te.mean()) * 100, 2),
        "accuracy": round(acc * 100, 2),
        "precision_at_60": round(conf_prec * 100, 2) if conf_prec is not None else None,
        "threshold": 0.6,
    }
    meta_path = os.path.join(MODELS_DIR, f"meta_{model_type}_meta.json")
    with open(meta_path, "w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2)
    if verbose:
        print(f"  META {model_type}: {meta}")
        print(f"  baseline (always take trades): {y_te.mean()*100:.1f}% win rate")
    return meta


def load_meta(model_type="xgboost"):
    """Load the meta model; returns predict(feature_dict)->prob or None."""
    if model_type == "xgboost":
        path = os.path.join(MODELS_DIR, "meta_xgboost.joblib")
    else:
        path = os.path.join(MODELS_DIR, "meta_gb.joblib")
    if not os.path.exists(path):
        return None
    import joblib
    model = joblib.load(path)

    def predict(feat):
        X = _matrix([feat])
        p = float(model.predict_proba(X)[0, 1])
        return {"meta_prob": round(p * 100, 1), "take": p >= 0.6}

    return predict


def meta_info(model_type="xgboost"):
    meta_path = os.path.join(MODELS_DIR, f"meta_{model_type}_meta.json")
    if os.path.exists(meta_path):
        with open(meta_path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    return None
